### ISSUE TITLE
[BUG] Values dont update

### ISSUE THREAD

**Issue by Ghost---Shadow** [NACH0CHEE5E/Production-Values#1]
I am using colony survival version 0.7.0

Even after waiting several days, there is nothing shown.

Here is my production stats.json

```json
{
  "1": {
    "NACH0.Types.ProductionStats": {
      "54": 2,
      "55": 2,
      "56": 3,
      "57": 3,
      "58": 3,
      "59": 4,
      "60": 4,
      "61": 4
    }
  }
}
```

**Comment by NACH0CHEE5E** [comment]
you have added the production ui type to be recorded,
you should be putting the item you want to record in the first inventory slot then typing the command, i will be releasing a new version in the coming day which ill make this easier as there will be a button in the ui

**Comment by Ghost---Shadow** [comment]
Can you make it record all items in the stockpile?

**Comment by NACH0CHEE5E** [comment]
Just download the 0.2.0 version and you can use the buttons to add/remove items, read the wiki for a more in-depth explanation
